### ISSUE TITLE
Focus on the search bar doesn't inhibit delete/backspace behavior

### ISSUE THREAD

**Issue by neurovertex** [shrewdlogarithm/steamtray#2]
Pressing delete or backspace to clear the search bar while having a game selected in the list will clear it's To Play/Completed/Binned status

**Comment by shrewdlogarithm** [comment]
Good catch!  Never trust event ordering!

Delete/BackSpace will clear and T/C/B will add other statuses (in a search or used as an initial to find something in a select)

Fixed in 30054bc9d7a3415fb1f18f25eb20b251955fc172
